### ISSUE TITLE
Bug with node v0.12.0 : cca push

### ISSUE THREAD

**Issue by jmorille** [MobileChromeApps/mobile-chrome-apps#527]
the command cca push work in node.js version v0.10.36
and in the same project with node.js in version v0.12.0 give the following error

``` console
user@mymachine:~/project/myproject/build/cca$ cca push
cca v0.5.1
GET http://adb_0019d2513c1f6e:2424/info ==> 200 (184)
/home/user/opt/node-v0.12.0-linux-x64/lib/node_modules/cca/node_modules/chrome-app-developer-tool-client/node_modules/agentkeepalive/lib/agent.js:63
    if (!self.isDestroyed(socket) &&
              ^
TypeError: undefined is not a function
    at Agent.<anonymous> (/home/a000cqp/opt/node-v0.12.0-linux-x64/lib/node_modules/cca/node_modules/chrome-app-developer-tool-client/node_modules/agentkeepalive/lib/agent.js:63:15)
    at Agent.emit (events.js:110:17)
    at Socket.onFree (_http_agent.js:202:10)
    at Socket.emit (events.js:104:17)
    at _http_client.js:453:14
    at process._tickCallback (node.js:355:11)
```

**Comment by clintwood** [comment]
The problem is that the `chrome-app-developer-tool-client` dependency here uses a very old version of `"agentkeepalive": "~0.2"` which does not use proper `semver` checking against the running node version information.

I just hacked it in the global `npm` registry on my machine for now. In file `<whatever>/npm/node_modules/cca/node_modules/chrome-app-developer-tool-client/node_modules/agentkeepalive/lib/agent.js` I changed from this 
```
if (process.version.indexOf('v0.8.') === 0 || process.version.indexOf('v0.10.') === 0) {
  OriginalAgent = require('./_http_agent').Agent;
  debug('%s use _http_agent', process.version);
}
to 
if (true || process.version.indexOf('v0.8.') === 0 || process.version.indexOf('v0.10.') === 0) {
  OriginalAgent = require('./_http_agent').Agent;
  debug('%s use _http_agent', process.version);
}
```
NOTE: the `true` in the if statement!
