### ISSUE TITLE
Issue upgrading project

### ISSUE THREAD

**Issue by wesleycho** [MobileChromeApps/mobile-chrome-apps#534]
I updated my cca and ran the upgrade command, I am getting this error.

<pre>
/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/lockfile/lockfile.js:46
      throw er
            ^
Error: Uh oh!
cannot find "/Users/wesleycho/repositories/incentives-web-app/platforms/android/org.chromium.i18n/copy-locales.gradle/project.properties" referenced in <framework>
    at Object.AndroidProject.addSubProject (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/android-project.js:70:51)
    at module.exports.framework.install (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:110:27)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:108:17)
</pre>

`copy-locales.gradle` is a file, so it looking for `copy-locales.gradle/project.properties` is incorrect.

**Comment by agrieve** [comment]
A change was made to the i18n plugin that breaks on older versions of CCA. 

The good news is that if you upgrade *again*, (to version 0.6.0), this should be fixed. 

The even better news is that the new version of CCA pins against the major version of relevant plugins, so breakages like this should not happen again.

**Comment by g105b** [comment]
I'm having this same issue, but I can't seem to upgrade to version 0.6.0 - how should this be done?
