### ISSUE TITLE
before_prepare/cca-check.js: [Error: Please install Android target: "android-21".

### ISSUE THREAD

**Issue by marcellodesales** [MobileChromeApps/mobile-chrome-apps#542]
Hi there,

I have installed Android 21.1 SDK: https://dl.google.com/android/android-sdk_r21.1-linux.tgz

However, I'm getting this error while trying to build :(

```
Running command: /pipeline/build/build/hooks/before_prepare/cca-check.js /pipeline/build/build
## Inject CSP for android
Running command: /pipeline/build/build/platforms/android/cordova/build 
[Error: Please install Android target: "android-21".

Hint: Open the SDK manager by running: /home/ubuntu/android-sdk-linux/tools/android
You will require:
1. "SDK Platform" for android-21
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)]
ERROR building one of the platforms: Error: /pipeline/build/build/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /pipeline/build/build/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/pipeline/build/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

Do I need to download the latest Platform and Build tools as 24.1.2, the latest, as well? 

http://developer.android.com/tools/sdk/tools-notes.html

Thanks

**Comment by marcellodesales** [comment]
My entire installation is as follows:

```
#!/bin/sh

export sdk_version="21.1"

# Install SDK
wget "http://dl.google.com/android/android-sdk_r${sdk_version}-linux.tgz"
tar zxf "android-sdk_r${sdk_version}-linux.tgz"
rm "android-sdk_r${sdk_version}-linux.tgz"

# Set environment variables
export ANDROID_HOME=${PWD}/android-sdk-linux
export ANDROID_BUILD_TOOLS="21.1.1"
export ANDROID_VERSION="4.4.2"
export ANDROID_PLATFORM_TOOLS="21.1.1"
export PATH="${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools"

type android || { echo "Path: $PATH"; echo 'Android not available after installation, terminating.'; exit 1; }

# Write environment variables to profile
echo "export ANDROID_HOME=\"${ANDROID_HOME}\"" | sudo tee -a /etc/profile.d/android.sh
echo "export ANDROID_SDK_VERSION=\"${sdk_version}\"" | sudo tee -a /etc/profile.d/android.sh
echo "export ANDROID_BUILD_TOOLS=\"${ANDROID_BUILD_TOOLS}\"" | sudo tee -a /etc/profile.d/android.sh
echo "export ANDROID_PLATFORM_TOOLS=\"${ANDROID_PLATFORM_TOOLS}\"" | sudo tee -a /etc/profile.d/android.sh
echo "export ANDROID_VERSION=\"${ANDROID_VERSION}\"" | sudo tee -a /etc/profile.d/android.sh
echo "export PATH=\"${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools\"" | sudo tee -a /etc/profile.d/android.sh

# Install android components
(while :
do
  echo 'y'
  sleep 2
done) | android update sdk -u -a -t 1,2,3,22,111,112
```

**Comment by marcellodesales** [comment]
I properly followed the instructions on http://stackoverflow.com/questions/17963508/how-to-install-android-sdk-build-tools-on-the-command-line... I selected the sdk to be update properly and created the proper Wercker Box https://github.com/quantogastei/box-cordova-cca/commit/acb429a2656b6b81c21d0ad4a46a421187e9c12c.

For those who wants to CI/CD to build and deploy CCA Apps automatically upon commits go to https://github.com/marcellodesales/box-cordova-cca for more info.

**Comment by marcellodesales** [comment]
The proper update command would be as follows:

```
android update sdk -u -a -t 5,23,114,116
```
