### ISSUE TITLE
Error running cca prepare/trying to add ios platform

### ISSUE THREAD

**Issue by shanling** [MobileChromeApps/mobile-chrome-apps#564]
Just experienced a new bug with cca that I haven't had before. When I try to run cca prepare in order to update the code before opening in XCode I get this error:

```
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:23)
    at runScript (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:131:16)
    at /usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
    at _fulfilled (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:749:13)
```

I've never gotten this error before, just started happening today. I tried removing the iOS platform and readding, but when I went to readd I got the same error.

**Comment by agrieve** [comment]
Sounds like probably there's a script within `hooks/` that doesn't have the executable bit set on it. Could also be that one of the plugins has a hook with the bit missing...
