### ISSUE TITLE
cca v0.7.0  'cca run (ios or android) --device' fails

### ISSUE THREAD

**Issue by bklynjones** [MobileChromeApps/mobile-chrome-apps#570]
Was having an issue deploying to ios device  so I upgraded (-g)   both ```cca``` and ```ios-deploy``` to their latest versions. 
After doing  so I ran ```checkenv```
``` shell
cca v0.7.0
Android Development: SDK configured properly.
iOS Development: SDK configured properly.
```
all good. 
I had an older version symlinked to a chrome app ( I like to develop on the desktop and then push to mobile when to test) so I ran ```cca create YourApp --link-to=path/to/manifest.json``` creating a new project in which to call cca run

Attempted Android 
```shell
bjones$ cca run android --device
cca v0.7.0
## Running Cordova Command: platform add android
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.0
/usr/local/lib/node_modules/cca/node_modules/q/q.js:141
                throw e;
                      ^
TypeError: undefined is not a function
    at Object.analyseManifest (/usr/local/lib/node_modules/cca/node_modules/cca-manifest-logic/src/analyse-manifest.js:97:31)
    at /usr/local/lib/node_modules/cca/src/pre-prepare.js:58:29
    at _fulfilled (/usr/local/lib/node_modules/cca/node_modules/q/q.js:820:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cca/node_modules/q/q.js:849:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cca/node_modules/q/q.js:782:13)
    at /usr/local/lib/node_modules/cca/node_modules/q/q.js:590:44
    at runSingle (/usr/local/lib/node_modules/cca/node_modules/q/q.js:123:13)
    at flush (/usr/local/lib/node_modules/cca/node_modules/q/q.js:111:13)
    at process._tickCallback (node.js:355:11)
```

and ios 
```shell
bjones$ cca run ios --device
cca v0.7.0
## Running Cordova Command: platform add ios
iOS project created with cordova-ios@3.8.0
/usr/local/lib/node_modules/cca/node_modules/q/q.js:141
                throw e;
                      ^
TypeError: undefined is not a function
    at Object.analyseManifest (/usr/local/lib/node_modules/cca/node_modules/cca-manifest-logic/src/analyse-manifest.js:97:31)
    at /usr/local/lib/node_modules/cca/src/pre-prepare.js:58:29
    at _fulfilled (/usr/local/lib/node_modules/cca/node_modules/q/q.js:820:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cca/node_modules/q/q.js:849:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cca/node_modules/q/q.js:782:13)
    at /usr/local/lib/node_modules/cca/node_modules/q/q.js:590:44
    at runSingle (/usr/local/lib/node_modules/cca/node_modules/q/q.js:123:13)
    at flush (/usr/local/lib/node_modules/cca/node_modules/q/q.js:111:13)
    at process._tickCallback (node.js:355:11)
```
Haven't seen this error before.

**Comment by agrieve** [comment]
Here's line 97:
https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/cca-manifest-logic/src/analyse-manifest.js#L97

Could you double check that line 97 looks the same on your machine?
(/usr/local/lib/node_modules/cca/node_modules/cca-manifest-logic/src/analyse-manifest.js)

Perhaps you have a number as your manifest.mobile.json's `"webview": ` setting?

**Comment by bklynjones** [comment]
[Update]:   It does.   I determined the error of my ways.  I had permissions enabled for unsupported APIs.
