### ISSUE TITLE
cca prepare unauthorized

### ISSUE THREAD

**Issue by darkoverlordofdata** [MobileChromeApps/mobile-chrome-apps#573]
I have cca installed with -g on linux mint.
$ cca checkenv
cca v0.7.0
Android Development: SDK configured properly.

cca push is awesome.
But when I run cca prepare, I get an unauthorized error. I get the same with sudo:

Fetching from npm failed: unauthorized Name or password is incorrect.: cordova-plugin-background-app
Error: unauthorized Name or password is incorrect.: cordova-plugin-background-app
    at RegClient.<anonymous> (/home/bruce/.nvm/v0.10.38/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
    at Request.self.callback (/home/bruce/.nvm/v0.10.38/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/bruce/.nvm/v0.10.38/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/bruce/.nvm/v0.10.38/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by darkoverlordofdata** [comment]
I tried using cordova directly and have the same issue. Looks like this is a cordova issue, not a cca issue.

**Comment by agrieve** [comment]
Try deleting your ~/.npmrc file
