### ISSUE TITLE
Error: EPERM, operation not permitted

### ISSUE THREAD

**Issue by PeEllAvaj** [MobileChromeApps/mobile-chrome-apps#582]
This is probably an environment thing for me, but I can't seem to get around it.

Fresh install off cca (0.7.1) with
```
    npm remove -g cca
    npm install -g cca
    npm create newproject
    cd newproject
    cd run android
```

sends me back with error
```
cca v0.7.1
## Running Cordova Command: platform add android

/usr/lib/node_modules/cca/node_modules/q/q.js:155
                throw e;
                      ^
Error: EPERM, operation not permitted '/usr/lib/node_modules/cca/cordova/cordova-android/bin/create'
    at Object.fs.chmodSync (fs.js:833:18)
    at Object.exports.spawn (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:98:12)
    at Q.then.then.then.then.prepOpts.platforms (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform.js:162:39)
    at _fulfilled (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/lib/node_modules/cca/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
```

**Comment by agrieve** [comment]
Weird - not sure how you got into this state, but I'd guess that running:

    chmod a+x /usr/lib/node_modules/cca/cordova/cordova-android/bin

would fix it.

**Comment by PeEllAvaj** [comment]
Tried making all of /usr/lib/node_modules/cca/ and my project folder 777 and it didn't help. I don't know what permission is failing. I can use the cordova-android/bin/create by hand.

As a debugging step I went back to 0.7.0 and created a fresh project, that failed, but my old cca projects worked... Weird...

**Comment by nicoceledon** [comment]
I had the version 0.7.0 working well, but when i installed the 0.7.1 got the same error.

**Comment by nicoceledon** [comment]
For now, i installed cca without `-g`

**Comment by bemasc** [comment]
Thanks @nicoceledon.  That approach (documented [here](http://stackoverflow.com/questions/19352976/npm-modules-wont-install-globally-without-sudo)) worked for me as a workaround.

**Comment by agrieve** [comment]
Looks like the bug was upstream in cordova's tools. I've filed & fixed the issue here: 
https://issues.apache.org/jira/browse/CB-9362

We'll need to wait for a new cordova release for `cca` to be fixed, but in the mean time installing with "-g" is a good work-around, as is using `nvm` to install node.
